
  export const userRows = [
    {
      id: 1,
      username: "Jon Snow",
      
      location:"Tunis",
      url:"aa",
      product_id:1,
      role:"le producteur",
      certifications:"bbbb",
      n_lots:1,
    },
    {
      id: 2,
      username: "Jon Snow",
     
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 3,
      username: "Jon Snow",
      
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 4,
      username: "Jon Snow",
      
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 5,
      username: "Jon Snow",
      
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 6,
      username: "Jon Snow",
      
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 7,
      username: "Jon Snow",
      
        
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 8,
      username: "Jon Snow",
      
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 9,
      username: "Jon Snow",
      
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
    {
      id: 10,
      username: "Jon Snow",
      
        location:"Tunis",
        url:"aa",
        product_id:1,
        role:"le producteur",
        certifications:"bbbb",
        n_lots:1,
    },
  ];

  export const productRows = [
    {
      id: 1,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
      

  
     
      
    },
    {
      id: 2,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 3,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 4,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 5,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 6,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 7,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 8,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 9,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
    {
      id: 10,
      date_production:"02/04/2022",
      lieu:"Tunis",
      date_extraction:"03/05/2022",
      date_control:"03/06/2022",
      technique_stockage:"aaa",
      n_lot:1,
      date_expiration:"05/07/2022",
    },
  ];